piVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: wwwanspedusv
  name: wwwanspedusv
spec:
  replicas: 1
  selector:
    app: wwwanspedusv
    deploymentconfig: wwwanspedusv
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: wwwanspedusv
        deploymentconfig: wwwanspedusv
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: wwwanspedusv:latest
      resources: {}
      source:
        git:
          ref: master
          uri: https://github.com/Eliseo247/www.ansp.edu.sv.git
        type: Git
      strategy:
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: mariadb-103-rhel7:latest
        type: Docker
      containers:
      - image: wwwanspedusv
        imagePullPolicy: Always
        name: wwwanspedusv
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /opt/app-root/src
          name: storage-wordpress
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: storage-wordpress 
        persistentVolumeClaim:
          claimName: storage-wordpress 
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - openshift: wwwanspedusv
      from:
        kind: ImageStreamTag
        name: wwwanspedusv:latest
    type: ImageChange
